# Generated by Django 6.0.4 on 2026-05-03 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket_keluhan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiketmodel',
            name='executor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiket_executor', to=settings.AUTH_USER_MODEL),
        ),
    ]
