# Generated by Django 6.0.4 on 2026-05-17 20:50

import django.db.models.deletion
import tiket_keluhan.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket_keluhan', '0002_alter_tiketmodel_executor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiketAttachmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tiket_keluhan.utils.custom_upload_path)),
                ('original_name', models.CharField(max_length=255, verbose_name='original name')),
                ('sotred_name', models.CharField(max_length=255, verbose_name='stored name')),
                ('tiket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='tiket_keluhan.tiketmodel')),
            ],
        ),
    ]
