# Generated by Django 6.0.4 on 2026-05-22 23:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket_keluhan', '0003_tiketattachmentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiketmodel',
            old_name='executor_id',
            new_name='executor',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='user_id',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='User Id'),
        ),
        migrations.AddField(
            model_name='tiketattachmentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiketmodel',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiket_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiketmodel',
            name='status',
            field=models.CharField(default='sent', max_length=50, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ReviewerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('tiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tiket_keluhan.tiketmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TiketActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='action type')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aktor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_actor', to=settings.AUTH_USER_MODEL)),
                ('tiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='tiket_keluhan.tiketmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TiketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_change', to=settings.AUTH_USER_MODEL)),
                ('tiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tiket_keluhan.tiketmodel')),
            ],
        ),
    ]
