# Generated by Django 6.0.4 on 2026-05-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket_keluhan', '0004_rename_executor_id_tiketmodel_executor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiketstatushistory',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='note'),
        ),
    ]
