# Generated by Django 6.0.4 on 2026-06-01 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket_keluhan', '0006_alter_reviewermodel_evaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiketactionmodel',
            name='aktor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_actor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tiketstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_change', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tiketstatushistory',
            name='tiket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tiket_keluhan.tiketmodel'),
        ),
    ]
