# Generated by Django 6.0.4 on 2026-06-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket_keluhan', '0007_alter_tiketactionmodel_aktor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiketactionmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
