# Generated by Django 6.0.4 on 2026-06-07 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket_keluhan', '0008_tiketactionmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiketstatushistory',
            name='tiket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_history', to='tiket_keluhan.tiketmodel'),
        ),
    ]
